import React from "react";

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      key="Poppins-Black"
      rel="preload"
      href="/fonts/Poppins-Black.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="Poppins-Bold"
      rel="preload"
      href="/fonts/Poppins-Bold.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="Poppins-ExtraBold"
      rel="preload"
      href="/fonts/Poppins-ExtraBold.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="Poppins-ExtraLight"
      rel="preload"
      href="/fonts/Poppins-ExtraLight.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="Poppins-Light"
      rel="preload"
      href="/fonts/Poppins-Light.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="Poppins-Medium"
      rel="preload"
      href="/fonts/Poppins-Medium.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="Poppins-Regular"
      rel="preload"
      href="/fonts/Poppins-Regular.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="Poppins-SemiBold"
      rel="preload"
      href="/fonts/Poppins-SemiBold.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="Poppins-Thin"
      rel="preload"
      href="/fonts/Poppins-Thin.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
  ]);
};
